=== AnaCR22/sew/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreEtapa" />
				<xs:element ref="numero" />
				<xs:element ref="longitudEtapa" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="velocidadGanador" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudadInicial" />
				<xs:element ref="ciudadFinal" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="sonidos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="hitos" />
				<xs:element ref="puntosAnonimos" />
				<xs:element ref="clasificadosEtapa" />
				<xs:element ref="clasificadosGeneral" />
				<xs:element ref="equipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreEtapa" type="xs:string" />
	<xs:element name="numero">
		<xs:simpleType>
			<xs:restriction base="xs:integer"> 
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="21"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="longitudEtapa">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDecimalNoNegativo">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="kilometros"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoDecimalNoNegativo">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempoGanador" type="xs:duration" />
	<xs:element name="velocidadGanador">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDecimalNoNegativo">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="kilometros/hora"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDecimalNoNegativo">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="metros"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ciudadInicial" type="xs:string" />
	<xs:element name="ciudadFinal" type="xs:string" />
	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="llana"/>
				<xs:enumeration value="montaña"/>
				<xs:enumeration value="contrarreloj individual"/>
				<xs:enumeration value="contrarreloj por equipos"/>
				<xs:enumeration value="media montaña"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fuente" type="xs:string" use="required" />
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sonidos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="sonido" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sonido">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="descripcion" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element ref="puertoMontana" />
					<xs:element ref="sprintIntermedio" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puertoMontana">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="categoria" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="1ª"/>
						<xs:enumeration value="2ª"/>
						<xs:enumeration value="3ª"/>
						<xs:enumeration value="especial"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="bonificado" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintIntermedio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
				<xs:element ref="distancia" />
			</xs:sequence>
			<xs:attribute name="bonificado" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitudPunto" />
				<xs:element ref="altitudPunto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitud">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="grados"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitudPunto" >
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="grados"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitud">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="metros"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name ="tipoLongitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180"/>
			<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name ="tipoLatitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90"/>
			<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name ="tipoAltitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-500"/>
			<xs:maxInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDecimalNoNegativo">
					<xs:attribute name="unidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="kilometros"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntosAnonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntoAnonimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoAnonimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="1" ref="nombrePunto" />
				<xs:element ref="punto" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombrePunto" type="xs:string" />
	<xs:element name="clasificadosEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primerClasificado" />
				<xs:element ref="segundoClasificado" />
				<xs:element ref="tercerClasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificadosGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primerClasificado" />
				<xs:element ref="segundoClasificado" />
				<xs:element ref="tercerClasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primerClasificado" type="xs:string" />
	<xs:element name="segundoClasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="diferencia" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tercerClasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="diferencia" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primerEquipo" />
				<xs:element ref="segundoEquipo" />
				<xs:element ref="tercerEquipo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="primerEquipo" type="xs:string" />
	<xs:element name="segundoEquipo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="diferencia" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tercerEquipo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="diferencia" type="xs:duration" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AnaCR22/sew/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<etapa xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombreEtapa>Dos Hermanas a Sevilla</nombreEtapa>
    <numero>17</numero>
    <longitudEtapa unidad="kilometros">185</longitudEtapa>
    <fecha>2026-09-09</fecha>
    <tiempoGanador>PT4H7M15S</tiempoGanador>
    <velocidadGanador unidad = "kilometros/hora">44.9</velocidadGanador>
    <desnivel unidad="metros">1084</desnivel>
    <ciudadInicial>Dos Hermanas</ciudadInicial>
    <ciudadFinal>Sevilla</ciudadFinal>
    <tipo>llana</tipo>
    <referencias>
        <referencia fuente="Wikipedia" descripcion="Información detallada sobre la ciudad de salida, Dos Hermanas.">
            https://es.wikipedia.org/wiki/Dos_Hermanas
        </referencia>
        <referencia fuente="Wikipedia" descripcion="Información detallada sobre la ciudad de meta, Sevilla.">
            https://es.wikipedia.org/wiki/Sevilla
        </referencia>
        <referencia fuente="Rtve" descripcion="Información detallada sobre la etapa 17 de La Vuelta 2026: perfil, recorrido, hora y dónde ver.">
            https://www.rtve.es/deportes/20260908/vuelta-2026-perfil-recorrido-hora-donde-ver-claves-etapa-17-sevilla/17177337.shtml
        </referencia>
    </referencias>

    <fotografias>
        <fotografia descripcion="Fotografia de la ciudad de salida: Dos Hermmanas">./multimedia/salida.jpg</fotografia>    
        <fotografia descripcion="Fotografia de la ciudad de meta: Sevilla">./multimedia/meta.jpg</fotografia>    
    </fotografias>

    <videos>
        <video descripcion="La Vuelta 2026 - Etapa 17: Recorrido y Altimetria">./multimedia/recorrido.mp4</video>    
    </videos>

    <sonidos>
        <sonido descripcion="La Vuelta 2026 - Sprint Final de la Etapa 17">./multimedia/final.m4a</sonido>
    </sonidos>

    <puntoOrigen>
    <punto>
        <longitudPunto unidad="grados">-5.924204</longitudPunto>
        <latitudPunto unidad="grados">37.226300</latitudPunto>
        <altitudPunto unidad="metros">31.205398</altitudPunto>
    </punto>
    </puntoOrigen>

    <puntoFinal>
        <punto>
            <longitudPunto unidad="grados">-5.999034</longitudPunto>
            <latitudPunto unidad="grados">37.385334</latitudPunto>
            <altitudPunto unidad="metros">8.140659</altitudPunto>
        </punto>
    </puntoFinal>

    <hitos>
        <sprintIntermedio bonificado="true">
            <punto>
                <longitudPunto unidad="grados">-5.950769</longitudPunto>
                <latitudPunto unidad="grados">37.483472</latitudPunto>
                <altitudPunto unidad="metros">11.8</altitudPunto>
            </punto>
            <distancia unidad="kilometros">165.9</distancia>
        </sprintIntermedio>
    </hitos>

    <puntosAnonimos>
        <puntoAnonimo>
            <nombrePunto>Los Palacios y Villafranca</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.923805</longitudPunto>
                <latitudPunto unidad="grados">37.159788</latitudPunto>
                <altitudPunto unidad="metros">11.0</altitudPunto>
            </punto>
            <distancia unidad="kilometros">7.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.838822</longitudPunto>
                <latitudPunto unidad="grados">37.179212</latitudPunto>
                <altitudPunto unidad="metros">21.4</altitudPunto>
            </punto>
            <distancia unidad="kilometros">15.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>Utrera</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.779895</longitudPunto>
                <latitudPunto unidad="grados">37.184908</latitudPunto>
                <altitudPunto unidad="metros">49.2</altitudPunto>
            </punto>
            <distancia unidad="kilometros">21.5</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.776030</longitudPunto>
                <latitudPunto unidad="grados">37.160582</latitudPunto>
                <altitudPunto unidad="metros">54.7</altitudPunto>
            </punto>
            <distancia unidad="kilometros">24.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.761861</longitudPunto>
                <latitudPunto unidad="grados">37.162215</latitudPunto>
                <altitudPunto unidad="metros">60.2</altitudPunto>
            </punto>
            <distancia unidad="kilometros">25.7</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>El Coronil</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.643961</longitudPunto>
                <latitudPunto unidad="grados">37.081868</latitudPunto>
                <altitudPunto unidad="metros">95.2</altitudPunto>
            </punto>
            <distancia unidad="kilometros">39.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.582428</longitudPunto>
                <latitudPunto unidad="grados">37.065058</latitudPunto>
                <altitudPunto unidad="metros">151.8</altitudPunto>
            </punto>
            <distancia unidad="kilometros">46.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.555225</longitudPunto>
                <latitudPunto unidad="grados">37.067950</latitudPunto>
                <altitudPunto unidad="metros">161.9</altitudPunto>
            </punto>
            <distancia unidad="kilometros">49.1</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.540963</longitudPunto>
                <latitudPunto unidad="grados">37.060332</latitudPunto>
                <altitudPunto unidad="metros">187.1</altitudPunto>
            </punto>
            <distancia unidad="kilometros">50.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>Caleras de la Sierra</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.479329</longitudPunto>
                <latitudPunto unidad="grados">37.098676</latitudPunto>
                <altitudPunto unidad="metros">166.0</altitudPunto>
            </punto>
            <distancia unidad="kilometros">58.0</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>Morón de la Frontera</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.463642</longitudPunto>
                <latitudPunto unidad="grados">37.121205</latitudPunto>
                <altitudPunto unidad="metros">217.1</altitudPunto>
            </punto>
            <distancia unidad="kilometros">61.2</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.520492</longitudPunto>
                <latitudPunto unidad="grados">37.117756</latitudPunto>
                <altitudPunto unidad="metros">141.4</altitudPunto>
            </punto>
            <distancia unidad="kilometros">66.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.603161</longitudPunto>
                <latitudPunto unidad="grados">37.151140</latitudPunto>
                <altitudPunto unidad="metros">90.3</altitudPunto>
            </punto>
            <distancia unidad="kilometros">74.8</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.632251</longitudPunto>
                <latitudPunto unidad="grados">37.140434</latitudPunto>
                <altitudPunto unidad="metros">88.6</altitudPunto>
            </punto>
            <distancia unidad="kilometros">77.6</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.647966</longitudPunto>
                <latitudPunto unidad="grados">37.176843</latitudPunto>
                <altitudPunto unidad="metros">79.0</altitudPunto>
            </punto>
            <distancia unidad="kilometros">82.3</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.800153</longitudPunto>
                <latitudPunto unidad="grados">37.304916</latitudPunto>
                <altitudPunto unidad="metros">44.7</altitudPunto>
            </punto>
            <distancia unidad="kilometros">101.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <punto>
                <longitudPunto unidad="grados">-5.815182</longitudPunto>
                <latitudPunto unidad="grados">37.327947</latitudPunto>
                <altitudPunto unidad="metros">59.1</altitudPunto>
            </punto>
            <distancia unidad="kilometros">104.9</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>Alcalá de Guadaira</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.826000</longitudPunto>
                <latitudPunto unidad="grados">37.346128</latitudPunto>
                <altitudPunto unidad="metros">93.4</altitudPunto>
            </punto>
            <distancia unidad="kilometros">109.4</distancia>
        </puntoAnonimo>
        <puntoAnonimo>
            <nombrePunto>Mairena del Alcor</nombrePunto>
            <punto>
                <longitudPunto unidad="grados">-5.748701</longitudPunto>
                <latitudPunto unidad="grados">37.376244</latitudPunto>
                <altitudPunto unidad="metros">134.1</altitudPunto>
            </punto>
